### PR TITLE
Add checkstyle setup

### PR DESCRIPTION
**Pull request by krichter722**
Please tell me which header to enforce in the `RegexpHeader` module to be added.

This change is [Reviewable](https://reviewable.io/reviews/unitsofmeasurement/jackson-module-unitsofmeasure/13)

### CODE REVIEW

**Comment by keilw** [comment]
src/main/java/com/opower/unitsofmeasure/UnitJacksonModule.java
and
src/test/java/com/opower/unitsofmeasure/TestUnitJacksonModule.java
are conflicting, so I only applied the Checkstyle part, assuming these two were already covered by another PR.

**Comment by krichter722** [comment]
Please just ping the next time with a comment so that I can rebase my PR branches on master when you're ready to merge instead of doing these manual applications. They destroy the commit messages and the overview in the history.

The need to add a part of the PR with commented out code should tell you that there's a conflict which needs to be resolved and that's why we use git. Anything else doesn't make sense.

**Comment by krichter722** [comment]
You also didn't reply to my question which header to enforce through `RegexpHeader`.

**Comment by keilw** [comment]
The whole checkstyle rules are far too restrictive I'm afraid, there are nearly 100 violations. As it is a discontinued project, there is not so much effort. If you can fix all of them, happy to merge a new PR with every single tab replaced by blank, etc. And comment in the Checkstyle plugin. 
Which header, those in Java files? Again, the project is discontinued, so the `LICENSE.txt` should do, no need to put an headers in the Java or other sources here.

**Pull request closed without merging**
